version: '3.8'
services:
  app:
    build: .
    command: "air -c golang/.air.toml"
    ports:
      - 9292:9292
    environment:
      TZ: Asia/Tokyo
      DB_NAME: isucon2021_prior
      DB_HOST: db
      DB_USER: isucon
      DB_PASS: isucon
    volumes:
      - ".:/go/src/github.com/giwa/isucon11p"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
#      - ./db/initialize:/docker-entrypoint-initdb.d
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      BIND-ADDRESS: 0.0.0.0
    ports:
      - 33060:3306
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"